Repository MultiCrew/copilot, pull requests merged in 2020-04, with the labels that each got.

#53 Implement beta application process and admin panel
  .env.example
  app/Http/Controllers/Auth/AccountController.php
  app/Http/Controllers/Auth/Admin/UserController.php
  app/Http/Controllers/Auth/Application/ApplicationAdminController.php
  app/Http/Controllers/Auth/Application/ApplicationController.php
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/Auth/ProfileController.php
  app/Http/Controllers/Auth/RegisterController.php
  app/Http/Controllers/Discord/DiscordController.php
  app/Http/Controllers/Flights/ArchivedFlightController.php
  app/Http/Controllers/Flights/FlightController.php
  app/Http/Controllers/Flights/FlightPlanController.php
  app/Http/Controllers/Notification/NotificationController.php
  app/Http/Kernel.php
  app/Models/Flights/Flight.php
  app/Models/Users/ApplicationForm.php
  app/Models/Users/User.php
  app/Models/Users/UserNotification.php
  app/Notifications/DiscordSendData.php
  app/Profile.php
  composer.json
  composer.lock
  config/captcha.php
  database/migrations/2014_10_12_000000_create_users_table.php
  database/migrations/2019_11_22_161701_create_permission_tables.php
  database/migrations/2019_12_01_173822_add_discord_id_to_roles_table.php
  database/migrations/2020_02_11_115135_create_user_notifications_table.php
  database/migrations/2020_03_24_224344_create_application_forms_table.php
  database/migrations/2020_03_28_133901_create_profiles_table.php
  database/seeds/FlightSeeder.php
  database/seeds/ProfileSeeder.php
  database/seeds/RoleSeeder.php
  database/seeds/UserSeeder.php
  resources/views/auth/account.blade.php
  resources/views/auth/applications/create.blade.php
  resources/views/auth/applications/index.blade.php
  resources/views/auth/applications/show.blade.php
  resources/views/auth/login.blade.php
  resources/views/auth/passwords/confirm.blade.php
  resources/views/auth/passwords/email.blade.php
  resources/views/auth/passwords/reset.blade.php
  resources/views/auth/register.blade.php
  resources/views/auth/users/index.blade.php
  resources/views/auth/users/show.blade.php
  resources/views/auth/verify.blade.php
  resources/views/flights/.archive/archive.blade.php
  resources/views/flights/.archive/list.blade.php
  resources/views/flights/user.blade.php
  resources/views/includes/admin-nav.blade.php
  resources/views/includes/nav.blade.php
  resources/views/includes/sidebar.blade.php
  resources/views/layouts/base.blade.php
  resources/views/welcome.blade.php
  routes/web.php
Labels: enhancement, security

#68 Add loading spinner overlay on submission of dispatch create form
  resources/views/dispatch/create.blade.php
Labels: enhancement, ui

#69 Fixes to plan notifications
  app/Http/Controllers/Flights/FlightPlanController.php
  app/Models/Flights/Flight.php
  resources/views/dispatch/index.blade.php
Labels: bug

#71 Make all navigation elements more responsive
  resources/sass/app.scss
  resources/views/includes/nav.blade.php
  resources/views/includes/sidebar.blade.php
  resources/views/layouts/base.blade.php
Labels: ui

#61 Discord integration
  .env.example
  .gitignore
  _ide_helper.php
  app/Channels/WebhookChannel.php
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/Discord/DiscordController.php
  app/Http/Controllers/Flights/FlightController.php
  app/Http/Controllers/Notification/NotificationController.php
  app/Models/Flights/Flight.php
  app/Notifications/DiscordSendData.php
  app/Notifications/RequestAccepted.php
  app/Providers/AuthServiceProvider.php
  composer.json
  composer.lock
  package-lock.json
  resources/js/app.js
  resources/sass/app.scss
  resources/views/auth/applications/create.blade.php
  resources/views/auth/users/show.blade.php
  resources/views/includes/nav.blade.php
  resources/views/welcome.blade.php
  routes/api.php
  routes/web.php
Labels: api, enhancement, requires-changes

#76 Fix for flight completion bug
  app/Models/Flights/Flight.php
  resources/views/flights/show.blade.php
Labels: bug

#74 Implemented private joining
  .gitignore
  app/Http/Controllers/Flights/FlightController.php
  app/Http/Traits/FlightTrait.php
  app/Notifications/RequestAccepted.php
  resources/views/flights/edit.blade.php
  resources/views/flights/show.blade.php
  routes/web.php
Labels: enhancement, requires-changes

#73 Add mail templates and basic essential email communications
  app/Mail/VerifyEmail.php
  app/Models/Users/User.php
  composer.json
  composer.lock
  database/migrations/2014_10_12_000000_create_users_table.php
  database/seeds/UserSeeder.php
  resources/views/mail/base.html
  resources/views/vendor/mail/html/button.blade.php
  resources/views/vendor/mail/html/footer.blade.php
  resources/views/vendor/mail/html/header.blade.php
  resources/views/vendor/mail/html/layout.blade.php
  resources/views/vendor/mail/html/message.blade.php
  resources/views/vendor/mail/html/panel.blade.php
  resources/views/vendor/mail/html/promotion.blade.php
  resources/views/vendor/mail/html/promotion/button.blade.php
  resources/views/vendor/mail/html/subcopy.blade.php
  resources/views/vendor/mail/html/table.blade.php
  resources/views/vendor/mail/html/themes/default.css
  resources/views/vendor/mail/text/button.blade.php
  resources/views/vendor/mail/text/footer.blade.php
  resources/views/vendor/mail/text/header.blade.php
  resources/views/vendor/mail/text/layout.blade.php
  resources/views/vendor/mail/text/message.blade.php
  resources/views/vendor/mail/text/panel.blade.php
  resources/views/vendor/mail/text/promotion.blade.php
  resources/views/vendor/mail/text/promotion/button.blade.php
  resources/views/vendor/mail/text/subcopy.blade.php
  resources/views/vendor/mail/text/table.blade.php
  resources/views/vendor/notifications/email.blade.php
  routes/web.php
Labels: enhancement

#77 Add project management guide
  .github/PROJECT_MANAGEMENT.md
Labels: documentation

#83 Hotfix from initial production deployment
  .env.example
  app/Http/Controllers/Auth/VerificationController.php
  app/Http/Controllers/Notification/NotificationController.php
  public/fonts/vendor/@fortawesome/fontawesome-free/webfa-brands-400.eot
  public/fonts/vendor/@fortawesome/fontawesome-free/webfa-brands-400.svg
  public/fonts/vendor/@fortawesome/fontawesome-free/webfa-brands-400.ttf
  public/fonts/vendor/@fortawesome/fontawesome-free/webfa-brands-400.woff
  public/fonts/vendor/@fortawesome/fontawesome-free/webfa-brands-400.woff2
  public/fonts/vendor/@fortawesome/fontawesome-free/webfa-regular-400.eot
  public/fonts/vendor/@fortawesome/fontawesome-free/webfa-regular-400.svg
  public/fonts/vendor/@fortawesome/fontawesome-free/webfa-regular-400.ttf
  public/fonts/vendor/@fortawesome/fontawesome-free/webfa-regular-400.woff
  public/fonts/vendor/@fortawesome/fontawesome-free/webfa-regular-400.woff2
  public/fonts/vendor/@fortawesome/fontawesome-free/webfa-solid-900.eot
  public/fonts/vendor/@fortawesome/fontawesome-free/webfa-solid-900.svg
  public/fonts/vendor/@fortawesome/fontawesome-free/webfa-solid-900.ttf
  public/fonts/vendor/@fortawesome/fontawesome-free/webfa-solid-900.woff
  public/fonts/vendor/@fortawesome/fontawesome-free/webfa-solid-900.woff2
  resources/views/flights/user.blade.php
  routes/web.php
Labels: bug, uncaught-exception

#88 Update to v0.1.3
  app/Http/Controllers/Auth/Application/ApplicationAdminController.php
Labels: bug, security

#89 Update to v0.1.4
  app/Models/Flights/Flight.php
Labels: bug

#95 Update to v0.1.6
  app/Http/Controllers/Flights/ArchivedFlightController.php
  app/Http/Controllers/Flights/FlightController.php
  app/Http/Kernel.php
  app/Providers/AppServiceProvider.php
  package-lock.json
  package.json
  resources/js/app.js
  resources/views/errors/401.blade.php
  resources/views/errors/403.blade.php
  resources/views/errors/404.blade.php
  resources/views/errors/419.blade.php
  resources/views/errors/429.blade.php
  resources/views/errors/500.blade.php
  resources/views/errors/503.blade.php
  resources/views/errors/illustrated-layout.blade.php
  resources/views/errors/layout.blade.php
  resources/views/errors/minimal.blade.php
  resources/views/flights/show.blade.php
  resources/views/flights/user.blade.php
  routes/web.php
Labels: work-in-progress

#103 Update to v0.1.7
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/Flights/FlightController.php
  app/Http/Traits/FlightTrait.php
  resources/views/auth/login.blade.php
  resources/views/auth/users/show.blade.php
  resources/views/dispatch/show.blade.php
  resources/views/flights/edit.blade.php
  resources/views/flights/show.blade.php
  resources/views/flights/user.blade.php
Labels: work-in-progress
